logging:
  filename: /root/lj/zeus/log/server.log
  errfilename: /root/lj/zeus/log/server_err.log
  maxsize: 10000000
  maxrolls: 5
  level: debug

daemon:
  switch: off

pprof:
  switch: off
  ip: 0.0.0.0
  port: 22222

httpserver:
  switch: on
  ip: 0.0.0.0
  port: 9999

scheduler:
  master: 42.81.11.2:5050
  address: 42.81.11.2
  authprincipal: zeus
  authsecretfile: /mesos/share/mesos/conf/zeus.secret

intervals:
  get_docker_containers_info: 10
  get_docker_images_info: 10

dbserver:
  switch: off
  log_sql_execute_time_switch: on
  conn_check_interval: 5
  dbitems:
    - DBName: mysql1
      DriverName: mysql
      DataSourceName: root:mysql@tcp(10.1.63.78:3306)/eop
      MaxIdleConns: 10
      MaxOpenConns: 10
    - DBName: mysql2
      DriverName: mysql
      DataSourceName: root:mysql@tcp(10.1.63.78:3306)/eop
      MaxIdleConns: 10
      MaxOpenConns: 10
    - DBName: sqlite3
      DriverName: sqlite3
      DataSourceName: /home/eop/lj/goserver/bin/a.db
      MaxIdleConns: 10
      MaxOpenConns: 10
